# Generated by Django 5.2.8 on 2025-12-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_product_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingavg',
            old_name='newrating',
            new_name='ratingavg',
        ),
    ]
