# Generated by Django 5.2.8 on 2025-12-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_newrating_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingavg',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ratingavg',
            old_name='user_id',
            new_name='user',
        ),
    ]
