# Generated by Django 5.2.8 on 2025-12-13 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_product_id_rating_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratingavg',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
